# Each route describes how an incoming URL will be processed by Platform.sh

"https://{default}/":
    type: upstream
    upstream: "ll_project:http"
  
"http://www.{default}/":
    type: redirect
    to: "https://{default}/"
    